# Generated by Django 4.1.3 on 2023-07-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='gst_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
